# Generated by Django 3.2.12 on 2022-04-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('firstname', models.CharField(max_length=65)),
                ('lastname', models.CharField(max_length=65)),
                ('email', models.UUIDField()),
            ],
        ),
    ]
